### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by thewhitetulip** [rohanthewiz/go_notes#2]
I tried building the repo, I get an error 
# github.com/mattn/go-sqlite3

Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte

**Comment by rohanthewiz** [comment]
Try with go 1.4.2

Sent via the Samsung Galaxy Mega™, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Suraj Patil notifications@github.com </div><div>Date:10/16/2015  11:17 AM  (GMT-06:00) </div><div>To: rohanthewiz/go_notes go_notes@noreply.github.com </div><div>Subject: [go_notes] Unable to build (#2) </div><div>
</div>I tried building the repo, I get an error

github.com/mattn/go-sqlite3

Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte

**Comment by thewhitetulip** [comment]
I am using go1.5
